# Generated by Django 3.1.7 on 2021-04-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('library', '0003_auto_20210401_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rented', models.DateTimeField(auto_created=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.book')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('currently_rented', models.ManyToManyField(through='renting.CurrentRental', to='library.Book')),
            ],
        ),
        migrations.AddField(
            model_name='currentrental',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.profile'),
        ),
    ]
