# Generated by Django 3.1.7 on 2021-04-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_auto_20210408_1613'),
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrental',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='library.bookinstance'),
        ),
        migrations.AlterField(
            model_name='currentrental',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='renting.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currently_rented',
            field=models.ManyToManyField(through='renting.CurrentRental', to='library.BookInstance'),
        ),
    ]
