# Generated by Django 3.1.7 on 2021-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_auto_20210408_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrental',
            name='date_rented',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
