# Generated by Django 3.1.7 on 2021-04-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_delete_inventory'),
        ('renting', '0003_auto_20210408_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrental',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='library.bookinstance'),
        ),
    ]
